# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XFSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_key', models.CharField(max_length=50)),
                ('site_title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XFStringTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='xfsitesettings',
            name='site_title_translations',
            field=models.ManyToManyField(blank=True, related_name='site_titles', to='xf_system.XFStringTable'),
        ),
    ]
