# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
    ]
