# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0001_squashed_0052_auto_20161115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspective',
            name='default_page',
            field=models.ForeignKey(help_text='The default page that will be displayed when a user logs on.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Page'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='database_key',
            field=models.CharField(help_text='The key from the settings file to use for the data connection for this widget.', max_length=150),
        ),
    ]
