# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0002_auto_20170812_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xfsitesettings',
            name='site_title_translations',
        ),
        migrations.AddField(
            model_name='xfsitesettings',
            name='site_title_strings',
            field=models.TextField(blank=True, help_text="Translations. Use a format as follows: 'pt':'translação', 'nl':'vertaling', -- each on a new line"),
        ),
        migrations.DeleteModel(
            name='XFStringTable',
        ),
    ]
