# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0002_navbarsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XFNavigationSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='NavBarItem',
        ),
        migrations.DeleteModel(
            name='NavBarSection',
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.NavigationSection'),
        ),
    ]
