# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0003_auto_20170808_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_filter_bar',
            field=models.BooleanField(default=True, help_text='Check this field if you want to display the filter bar. Otherwise it will be hidden.'),
            preserve_default=False,
        ),
    ]
