# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0003_auto_20170814_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfsitesettings',
            name='site_title_strings',
            field=models.TextField(blank=True, help_text="Translations. Use a format as follows: 'pt':'tradução', 'nl':'vertaling', -- each on a new line"),
        ),
    ]
