# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0003_auto_20160708_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.NavigationItem'),
        ),
    ]
