# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0004_page_show_filter_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, help_text='Specifies a parent page for this item. Leave this empty if a page is immediately below a navigation section ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childma_page', to='uc_dashboards.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='navigation_section',
            field=models.ForeignKey(blank=True, help_text='Specifies the navigation item to link this item to. Do not specify this if a parent page is set', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='uc_dashboards.NavigationSection'),
        ),
    ]
