# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0004_navigationitem_parent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
