# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0004_auto_20170814_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfsitesettings',
            name='site_icon',
            field=models.CharField(blank=True, default='fa_world', help_text='The site icon to be used', max_length=50, null=True),
        ),
    ]
