# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0005_xfsitesettings_site_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfsitesettings',
            name='site_default_language',
            field=models.CharField(default='en', help_text='The default language code for the site.', max_length=5),
        ),
        migrations.AlterField(
            model_name='xfsitesettings',
            name='site_icon',
            field=models.CharField(blank=True, default='fa-globe', help_text='The site icon to be used', max_length=50, null=True),
        ),
    ]
