# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0006_page_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='allow_anonymous',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.PageSection'),
        ),
        migrations.AlterField(
            model_name='page',
            name='permissions_to_view',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, max_length=10400),
        ),
    ]
