# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0007_auto_20160708_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='main_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
