# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0008_page_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
