# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0009_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='navigation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.NavigationItem'),
        ),
    ]
