# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0010_page_navigation_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
