# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0011_auto_20160708_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='navigation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='uc_dashboards.NavigationItem'),
        ),
    ]
