# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0012_auto_20160708_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Template'),
            preserve_default=False,
        ),
    ]
