# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0013_auto_20171108_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationsection',
            old_name='caption_nl',
            new_name='caption_nl_nl',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='about_nl',
            new_name='about_nl_nl',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='data_sources_nl',
            new_name='data_sources_nl_nl',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='main_title_nl',
            new_name='main_title_nl_nl',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='text_nl',
            new_name='text_nl_nl',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_nl',
            new_name='title_nl_nl',
        ),
        migrations.RenameField(
            model_name='pagesection',
            old_name='title_nl',
            new_name='title_nl_nl',
        ),
        migrations.RenameField(
            model_name='pagestatus',
            old_name='name_nl',
            new_name='name_nl_nl',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='name_nl',
            new_name='name_nl_nl',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='sub_text_nl',
            new_name='sub_text_nl_nl',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='text_nl',
            new_name='text_nl_nl',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='title_nl',
            new_name='title_nl_nl',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='user_description_nl',
            new_name='user_description_nl_nl',
        ),
    ]
