# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0014_auto_20171108_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_attributes',
            field=models.TextField(blank=True, help_text='Any custom attributes, which may be forwarded to the template. Must be a Python dictionary format.'),
        ),
        migrations.AddField(
            model_name='page',
            name='widgets',
            field=models.TextField(blank=True, help_text='A python dictionary specifiying widget slugs for this template.'),
        ),
    ]
