# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0015_page_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetype',
            name='url_section',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
