# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0016_pagetype_url_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='navigation_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='uc_dashboards.NavigationItem'),
        ),
    ]
