# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0016_auto_20171114_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='built_in',
            field=models.BooleanField(default=False, help_text='Specifies whether this is a built-in template, which should not be modified'),
        ),
    ]
