# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0017_auto_20160708_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.PageSection'),
            preserve_default=False,
        ),
    ]
