# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0018_auto_20171114_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationsection',
            old_name='caption_pt_pt',
            new_name='caption_pt',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='about_pt_pt',
            new_name='about_pt',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='data_sources_pt_pt',
            new_name='data_sources_pt',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='main_title_pt_pt',
            new_name='main_title_pt',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='text_pt_pt',
            new_name='text_pt',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_pt_pt',
            new_name='title_pt',
        ),
        migrations.RenameField(
            model_name='pagesection',
            old_name='title_pt_pt',
            new_name='title_pt',
        ),
        migrations.RenameField(
            model_name='pagestatus',
            old_name='name_pt_pt',
            new_name='name_pt',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='name_pt_pt',
            new_name='name_pt',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='sub_text_pt_pt',
            new_name='sub_text_pt',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='text_pt_pt',
            new_name='text_pt',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='title_pt_pt',
            new_name='title_pt',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='user_description_pt_pt',
            new_name='user_description_pt',
        ),
    ]
