# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0018_auto_20160710_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(blank=True, help_text='The page ID can be used in the view to load a specific set of context data, e.g. a dashboard', max_length=20, null=True),
        ),
    ]
