# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0019_page_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsection',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, help_text='Specify a parent navigation section, or leave it empty if it is a top section', null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.NavigationSection'),
        ),
    ]
