# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0008_auto_20171120_0742'),
        ('uc_dashboards', '0020_perspective_slug'),
    ]

    operations = [
    ]
