# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0020_auto_20160712_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, help_text='Specify a parent navigation section, or leave it empty if it is a top section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sections', to='uc_dashboards.NavigationSection'),
        ),
    ]
