# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0021_merge_20180110_2034'),
        ('uc_dashboards', '0021_merge_20171213_1148'),
    ]

    operations = [
    ]
