# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0021_auto_20160712_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='navigation_item',
        ),
        migrations.AddField(
            model_name='page',
            name='navigation_section',
            field=models.OneToOneField(blank=True, help_text='Specifies the navigation item to link this item to. ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='uc_dashboards.NavigationSection'),
        ),
    ]
