# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0022_auto_20160712_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='navigation_section',
            field=models.ForeignKey(blank=True, help_text='Specifies the navigation item to link this item to. ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='uc_dashboards.NavigationSection'),
        ),
    ]
