# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0023_auto_20160712_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='parent_item',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='section',
        ),
        migrations.DeleteModel(
            name='NavigationItem',
        ),
    ]
