# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('uc_dashboards', '0024_auto_20160712_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the widget.', max_length=150)),
                ('slug', models.SlugField(help_text='This field identifies part of the URL that makes it friendly', max_length=150)),
                ('allow_anonymous', models.BooleanField(help_text='Specifies whether anonymous browsing is allowed for this widget')),
                ('widget_id', models.CharField(blank=True, help_text='Can be used in the view to load a specific set of context data', max_length=50, null=True)),
                ('permissions_to_view', models.ManyToManyField(blank=True, help_text='Specifies the groups that may view this widget', to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='template_text',
            field=models.TextField(blank=True, help_text='Allows you to specificy the content of a template.'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('1', 'Page'), ('2', 'Dashboard'), ('3', 'Widget'), ('0', 'Other')], default='1', help_text='The type of template', max_length=2),
        ),
        migrations.AlterField(
            model_name='page',
            name='allow_anonymous',
            field=models.BooleanField(help_text='Specifies whether anonymous browsing is allowed for this page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='main_title',
            field=models.CharField(help_text='Main title on top of the page', max_length=150),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.CharField(blank=True, help_text='Can be used in the view to load a specific set of context data, e.g. a dashboard', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.ForeignKey(default=1, help_text='Determines if this is a normal page, or a dashboard', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.PageType'),
        ),
        migrations.AlterField(
            model_name='page',
            name='permissions_to_view',
            field=models.ManyToManyField(blank=True, help_text='Specifies the groups that may view this page', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='page',
            name='section',
            field=models.ForeignKey(help_text='Taxonomy classification of this page. Helps to form a pretty URL.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.PageSection'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='This field identifies part of the URL that makes it friendly', max_length=150),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(help_text='The template to be used to render this page. May be overridden by the view.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title of the page. Also appears in the navigation bar.', max_length=150),
        ),
        migrations.AddField(
            model_name='widget',
            name='template',
            field=models.ForeignKey(help_text='The template to be used to render this widget. May be overridden by the view.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Template'),
        ),
    ]
