# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0025_auto_20160731_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('1', 'Pie'), ('2', 'Table'), ('0', 'Other')], default='0', help_text='The type of widget', max_length=2),
        ),
    ]
