# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0026_widget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='data_columns',
            field=models.TextField(blank=True, help_text="Tables/Pie: Data columns to use. One per line. 'Title', 'Width', 'Column name'"),
        ),
        migrations.AddField(
            model_name='widget',
            name='data_point_column',
            field=models.TextField(blank=True, help_text='Pie: the column that has the data points for a pie'),
        ),
        migrations.AddField(
            model_name='widget',
            name='sql_query',
            field=models.TextField(blank=True, help_text='Tables/Pie: The SQL query to run with this widget'),
        ),
        migrations.AddField(
            model_name='widget',
            name='sub_text',
            field=models.TextField(blank=True, help_text='Pie: text to show below the pie.'),
        ),
    ]
