# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0027_auto_20160731_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='label_column',
            field=models.TextField(blank=True, help_text='Pie: the column that has the labels to be shown in the pie'),
        ),
    ]
