# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0028_widget_label_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_source',
            field=models.CharField(choices=[('1', 'File within Django app (template file)'), ('2', 'Load from database (specify here)')], default='1', help_text='Specifies whether the template should be loaded from the file system, or from the database.', max_length=2),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
