# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0029_auto_20160731_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='database_key',
            field=models.CharField(default='ptbi_data', help_text='The key from the settings file to use for the data connection for this widget.', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='text',
            field=models.TextField(blank=True, help_text='If this is a text widget, the text will be displayed in the widget. Useful for static widgets.'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('1', 'Page'), ('2', 'Dashboard'), (('3',), 'Widget'), ('0', 'Other')], default='1', help_text='The type of template', max_length=2),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('1', 'Pie'), ('2', 'Table'), ('3', 'Tiles'), ('0', 'Other')], default='0', help_text='The type of widget', max_length=2),
        ),
    ]
