# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0030_auto_20160807_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='custom_attributes',
            field=models.TextField(blank=True, help_text='Any custom attributes. Must be a Python dictionary format.'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('1', 'Page'), ('2', 'Dashboard'), ('3', 'Widget'), ('0', 'Other')], default='1', help_text='The type of template', max_length=2),
        ),
        migrations.AlterField(
            model_name='widget',
            name='data_columns',
            field=models.TextField(blank=True, help_text='Tables/Pie: Data columns to use. One per line. Must be a Python dictionary format.'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='data_point_column',
            field=models.TextField(blank=True, help_text='Pie: the column that has the data points for a pie. Must be a Python dictionary format.'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('1', 'Pie'), ('2', 'Table'), ('3', 'Tiles'), ('4', 'Easy pie'), ('5', 'Line graph'), ('6', 'Bar graph'), ('7', 'Doughnut graph'), ('8', 'Map'), ('9', 'Text block'), ('0', 'Other')], default='0', help_text='The type of widget', max_length=2),
        ),
    ]
