# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0032_auto_20160812_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='filters',
            field=models.CharField(blank=True, help_text='Quoted and comma-separated list of string values with filter names from the query string', max_length=512, null=True),
        ),
    ]
