# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0033_widget_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='code',
            field=models.CharField(blank=True, help_text='A code that can be used to identify this widget. The code will be displayed in the "About this widget" box.', max_length=255),
        ),
        migrations.AddField(
            model_name='widget',
            name='user_description',
            field=models.TextField(blank=True, help_text='A description that helps the user understand what this widget shows. It will be shown in a pop-up window. '),
        ),
        migrations.AddField(
            model_name='widget',
            name='view_details_url',
            field=models.CharField(blank=True, help_text='A URL specifiying a details link. This could be another dashboard, or a JasperReport. ', max_length=255),
        ),
    ]
