# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0034_auto_20160902_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='navigation_sections', to='uc_dashboards.Tag'),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='uc_dashboards.Tag'),
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='uc_dashboards.Tag'),
        ),
        migrations.AddField(
            model_name='widget',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='widgets', to='uc_dashboards.Tag'),
        ),
    ]
