# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('uc_dashboards', '0035_auto_20160902_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_filter', models.CharField(blank=True, help_text='A dashboard filter that will always be applied to the users of this group. This allows you to filter for a specific purpose', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('tags', models.ManyToManyField(blank=True, related_name='group_profiles', to='uc_dashboards.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='template_source',
            field=models.CharField(choices=[('1', 'File system'), ('2', 'From database')], default='1', help_text='Specifies whether the template should be loaded from the file system, or from the database.', max_length=2),
        ),
    ]
