# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0037_auto_20161101_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='present_filter',
            new_name='preset_filter',
        ),
    ]
