# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0038_auto_20161101_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group'),
        ),
    ]
