# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('uc_dashboards', '0039_auto_20161101_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this perspective.', max_length=150)),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The group or groups that these perspective should be made available to.', related_name='groups', to='auth.Group')),
                ('pages', models.ManyToManyField(blank=True, help_text='The pages that are part of this perspective.', related_name='pages', to='uc_dashboards.Page')),
                ('tags', models.ManyToManyField(blank=True, related_name='perspectives', to='uc_dashboards.Tag')),
            ],
        ),
    ]
