# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0040_perspective'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='code',
            field=models.CharField(blank=True, help_text='A code for this perspective.', max_length=30),
        ),
    ]
