# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0041_perspective_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='default_page',
            field=models.ForeignKey(default=0, help_text='The default page that will be displayed when a user logs on.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Page'),
            preserve_default=False,
        ),
    ]
