# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0042_perspective_default_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspective',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The group or groups that these perspective should be made available to.', related_name='perspectives', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='perspective',
            name='pages',
            field=models.ManyToManyField(blank=True, help_text='The pages that are part of this perspective.', related_name='perspectives', to='uc_dashboards.Page'),
        ),
    ]
