# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('uc_dashboards', '0043_auto_20161102_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPerspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_filter', models.TextField(blank=True, help_text='A dashboard filter that will always be applied to this perspective for this group.')),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('group', models.ForeignKey(help_text='The group to which to apply this perspective.', on_delete=django.db.models.deletion.CASCADE, related_name='group_perspectives', to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='preset_filter',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='groups',
        ),
        migrations.AddField(
            model_name='groupperspective',
            name='perspective',
            field=models.ForeignKey(help_text='The perspective to apply.', on_delete=django.db.models.deletion.CASCADE, related_name='group_perspectives', to='uc_dashboards.Perspective'),
        ),
        migrations.AddField(
            model_name='groupperspective',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='group_perspectives', to='uc_dashboards.Tag'),
        ),
    ]
