# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0044_auto_20161103_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperspective',
            name='name',
            field=models.CharField(default='Perspective', help_text='The name of this group perspective, e.g. Jinja health facility.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perspective',
            name='name',
            field=models.CharField(help_text='The name of this perspective.', max_length=255),
        ),
    ]
