# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uc_dashboards', '0045_auto_20161103_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_filters', models.TextField(blank=True, help_text='Can set preset filters for perspectives. Filters will be applied onto perspectives')),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('tags', models.ManyToManyField(blank=True, related_name='user_profiles', to='uc_dashboards.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='preset_filters',
            field=models.TextField(blank=True, help_text='Can set preset filters for perspectives. Filters will be applied onto perspectives'),
        ),
    ]
