# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('uc_dashboards', '0046_auto_20161105_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='perspectives',
            field=models.ManyToManyField(blank=True, related_name='group_perspectives', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='groupperspective',
            name='group',
            field=models.ForeignKey(help_text='The group to which to apply this perspective.', on_delete=django.db.models.deletion.CASCADE, related_name='group_perspectives_nn', to='auth.Group'),
        ),
    ]
