# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0047_auto_20161105_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupperspective',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupperspective',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='groupperspective',
            name='tags',
        ),
        migrations.DeleteModel(
            name='GroupPerspective',
        ),
    ]
