# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0048_auto_20161105_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='perspectives',
            field=models.ManyToManyField(blank=True, related_name='group_perspectives', to='uc_dashboards.Perspective'),
        ),
    ]
