# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0049_auto_20161105_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspective',
            name='code',
            field=models.CharField(blank=True, help_text='A code for this perspective. The code will be used to preset filters.', max_length=128),
        ),
    ]
