# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0050_auto_20161105_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_perspective',
            field=models.ForeignKey(blank=True, help_text='The default perspective for this user. May be null if the user only has one perspective from their groups. If the perspective is not part of a group, the default perspective will be added.', null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Perspective'),
        ),
    ]
