# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfstringtable',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
