# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0007_xfsitesettings_custom_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfsitesettings',
            name='footer_details',
            field=models.TextField(blank=True, help_text='Details that will be added to the site footer', null=True),
        ),
    ]
