# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    #replaces = [(b'uc_dashboards', '0001_initial'), (b'uc_dashboards', '0002_navbarsection'), (b'uc_dashboards', '0003_auto_20160708_0050'), (b'uc_dashboards', '0004_navigationitem_parent_item'), (b'uc_dashboards', '0005_auto_20160708_0054'), (b'uc_dashboards', '0006_page_pagesection'), (b'uc_dashboards', '0007_auto_20160708_1644'), (b'uc_dashboards', '0008_page_main_title'), (b'uc_dashboards', '0009_page_slug'), (b'uc_dashboards', '0010_page_navigation_item'), (b'uc_dashboards', '0011_auto_20160708_1744'), (b'uc_dashboards', '0012_auto_20160708_1831'), (b'uc_dashboards', '0013_page_template'), (b'uc_dashboards', '0014_pagetype'), (b'uc_dashboards', '0015_page_page_type'), (b'uc_dashboards', '0016_pagetype_url_section'), (b'uc_dashboards', '0017_auto_20160708_2121'), (b'uc_dashboards', '0018_auto_20160710_0349'), (b'uc_dashboards', '0019_page_page_id'), (b'uc_dashboards', '0020_auto_20160712_0326'), (b'uc_dashboards', '0021_auto_20160712_0327'), (b'uc_dashboards', '0022_auto_20160712_0333'), (b'uc_dashboards', '0023_auto_20160712_0349'), (b'uc_dashboards', '0024_auto_20160712_0402'), (b'uc_dashboards', '0025_auto_20160731_1659'), (b'uc_dashboards', '0026_widget_widget_type'), (b'uc_dashboards', '0027_auto_20160731_1716'), (b'uc_dashboards', '0028_widget_label_column'), (b'uc_dashboards', '0029_auto_20160731_2026'), (b'uc_dashboards', '0030_auto_20160807_2232'), (b'uc_dashboards', '0031_auto_20160809_2332'), (b'uc_dashboards', '0032_auto_20160812_2131'), (b'uc_dashboards', '0033_widget_filters'), (b'uc_dashboards', '0034_auto_20160902_0633'), (b'uc_dashboards', '0035_auto_20160902_1121'), (b'uc_dashboards', '0036_auto_20161101_2336'), (b'uc_dashboards', '0037_auto_20161101_2338'), (b'uc_dashboards', '0038_auto_20161101_2339'), (b'uc_dashboards', '0039_auto_20161101_2346'), (b'uc_dashboards', '0040_perspective'), (b'uc_dashboards', '0041_perspective_code'), (b'uc_dashboards', '0042_perspective_default_page'), (b'uc_dashboards', '0043_auto_20161102_2121'), (b'uc_dashboards', '0044_auto_20161103_1721'), (b'uc_dashboards', '0045_auto_20161103_1813'), (b'uc_dashboards', '0046_auto_20161105_1722'), (b'uc_dashboards', '0047_auto_20161105_1735'), (b'uc_dashboards', '0048_auto_20161105_1739'), (b'uc_dashboards', '0049_auto_20161105_1743'), (b'uc_dashboards', '0050_auto_20161105_1748'), (b'uc_dashboards', '0051_userprofile_default_perspective'), (b'uc_dashboards', '0052_auto_20161115_2238')]

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=10400)),
                ('permissions_to_view', models.ManyToManyField(to='auth.Group')),
                ('allow_anonymous', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(help_text='Taxonomy classification of this page. Helps to form a pretty URL.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.PageSection'),
        ),
        migrations.AlterField(
            model_name='page',
            name='permissions_to_view',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, max_length=10400),
        ),
        migrations.AddField(
            model_name='page',
            name='main_title',
            field=models.CharField(help_text='Main title on top of the page', max_length=150),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='This field identifies part of the URL that makes it friendly', max_length=150),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template_path', models.CharField(blank=True, max_length=255)),
                ('template_text', models.TextField(blank=True, help_text='Allows you to specificy the content of a template.')),
                ('template_type', models.CharField(choices=[('1', 'Page'), ('2', 'Dashboard'), ('3', 'Widget'), ('0', 'Other')], default='1', help_text='The type of template', max_length=2)),
                ('template_source', models.CharField(choices=[('1', 'File within Django app (template file)'), ('2', 'Load from database (specify here)')], default='1', help_text='Specifies whether the template should be loaded from the file system, or from the database.', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(help_text='The template to be used to render this page. May be overridden by the view.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Template'),
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url_section', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.ForeignKey(default=1, help_text='Determines if this is a normal page, or a dashboard', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.PageType'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(blank=True, help_text='Can be used in the view to load a specific set of context data, e.g. a dashboard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, help_text='Specify a parent navigation section, or leave it empty if it is a top section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sections', to='uc_dashboards.NavigationSection'),
        ),
        migrations.AddField(
            model_name='page',
            name='navigation_section',
            field=models.ForeignKey(blank=True, help_text='Specifies the navigation item to link this item to. ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='uc_dashboards.NavigationSection'),
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the widget.', max_length=150)),
                ('slug', models.SlugField(help_text='This field identifies part of the URL that makes it friendly', max_length=150)),
                ('allow_anonymous', models.BooleanField(help_text='Specifies whether anonymous browsing is allowed for this widget')),
                ('widget_id', models.CharField(blank=True, help_text='Can be used in the view to load a specific set of context data', max_length=50, null=True)),
                ('permissions_to_view', models.ManyToManyField(blank=True, help_text='Specifies the groups that may view this widget', to='auth.Group')),
                ('template', models.ForeignKey(help_text='The template to be used to render this widget. May be overridden by the view.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Template')),
                ('widget_type', models.CharField(choices=[('1', 'Pie'), ('2', 'Table'), ('3', 'Tiles'), ('4', 'Easy pie'), ('5', 'Line graph'), ('6', 'Bar graph'), ('7', 'Doughnut graph'), ('10', 'Progress circle'), ('8', 'Map'), ('9', 'Text block'), ('0', 'Other')], default='0', help_text='The type of widget', max_length=2)),
                ('data_columns', models.TextField(blank=True, help_text='Tables/Pie: Data columns to use. One per line. Must be a Python dictionary format.')),
                ('data_point_column', models.TextField(blank=True, help_text='Pie: the column that has the data points for a pie. Must be a Python dictionary format.')),
                ('sql_query', models.TextField(blank=True, help_text='Tables/Pie: The SQL query to run with this widget')),
                ('sub_text', models.TextField(blank=True, help_text='Pie: text to show below the pie.')),
                ('label_column', models.TextField(blank=True, help_text='Pie: the column that has the labels to be shown in the pie')),
                ('database_key', models.CharField(default='ptbi_data', help_text='The key from the settings file to use for the data connection for this widget.', max_length=150)),
                ('text', models.TextField(blank=True, help_text='If this is a text widget, the text will be displayed in the widget. Useful for static widgets.')),
                ('custom_attributes', models.TextField(blank=True, help_text='Any custom attributes. Must be a Python dictionary format.')),
                ('filters', models.CharField(blank=True, help_text='Quoted and comma-separated list of string values with filter names from the query string', max_length=512, null=True)),
                ('code', models.CharField(blank=True, help_text='A code that can be used to identify this widget. The code will be displayed in the "About this widget" box.', max_length=255)),
                ('user_description', models.TextField(blank=True, help_text='A description that helps the user understand what this widget shows. It will be shown in a pop-up window. ')),
                ('view_details_url', models.CharField(blank=True, help_text='A URL specifiying a details link. This could be another dashboard, or a JasperReport. ', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='allow_anonymous',
            field=models.BooleanField(help_text='Specifies whether anonymous browsing is allowed for this page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='permissions_to_view',
            field=models.ManyToManyField(blank=True, help_text='Specifies the groups that may view this page', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title of the page. Also appears in the navigation bar.', max_length=150),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='navigation_sections', to='uc_dashboards.Tag'),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='uc_dashboards.Tag'),
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='uc_dashboards.Tag'),
        ),
        migrations.AddField(
            model_name='widget',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='widgets', to='uc_dashboards.Tag'),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('tags', models.ManyToManyField(blank=True, related_name='group_profiles', to='uc_dashboards.Tag')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group')),
                ('preset_filters', models.TextField(blank=True, help_text='Can set preset filters for perspectives. Filters will be applied onto perspectives')),
                ('perspectives', models.ManyToManyField(blank=True, related_name='group_perspectives', to='uc_dashboards.Perspective')),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='template_source',
            field=models.CharField(choices=[('1', 'File system'), ('2', 'From database')], default='1', help_text='Specifies whether the template should be loaded from the file system, or from the database.', max_length=2),
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this perspective.', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('pages', models.ManyToManyField(blank=True, help_text='The pages that are part of this perspective.', related_name='perspectives', to='uc_dashboards.Page')),
                ('tags', models.ManyToManyField(blank=True, related_name='perspectives', to='uc_dashboards.Tag')),
                ('code', models.CharField(blank=True, help_text='A code for this perspective. The code will be used to preset filters.', max_length=128)),
                ('default_page', models.ForeignKey(default=0, help_text='The default page that will be displayed when a user logs on.', on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Page')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_filters', models.TextField(blank=True, help_text='Can set preset filters for perspectives. Filters will be applied onto perspectives')),
                ('comment', models.TextField(blank=True, help_text='Any comment.')),
                ('tags', models.ManyToManyField(blank=True, related_name='user_profiles', to='uc_dashboards.Tag')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('default_perspective', models.ForeignKey(blank=True, help_text='The default perspective for this user. May be null if the user only has one perspective from their groups. If the perspective is not part of a group, the default perspective will be added.', null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_dashboards.Perspective')),
            ],
        ),
    ]

