# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:08
from __future__ import unicode_literals

from django.db import migrations
import xf.uc_dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0002_auto_20170815_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='text',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='If this is a text widget, the text will be displayed in the widget. Useful for static widgets.'),
        ),
    ]
