# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:19
from __future__ import unicode_literals

from django.db import migrations
import xf.uc_dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0003_auto_20170903_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='user_description',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='A description that helps the user understand what this widget shows. It will be shown in a pop-up window. '),
        ),
    ]
