# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0005_auto_20170809_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.IntegerField(blank=True, default=0, help_text='Pages with a lower index will be added to the navigation tree before those with a higher index. This is used to sort the navigation tree.'),
        ),
    ]

