# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import xf.uc_dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0007_auto_20171030_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='title_en',
            field=models.CharField(help_text='Title of the widget.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='title_nl',
            field=models.CharField(help_text='Title of the widget.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='title_pt',
            field=models.CharField(help_text='Title of the widget.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='user_description_en',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='A description that helps the user understand what this widget shows. It will be shown in a pop-up window. ', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='user_description_nl',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='A description that helps the user understand what this widget shows. It will be shown in a pop-up window. ', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='user_description_pt',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='A description that helps the user understand what this widget shows. It will be shown in a pop-up window. ', null=True),
        ),
    ]
