# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import xf.uc_dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0008_auto_20171107_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsection',
            name='caption_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='caption_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='caption_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='main_title_en',
            field=models.CharField(help_text='Main title on top of the page', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='main_title_nl',
            field=models.CharField(help_text='Main title on top of the page', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='main_title_pt',
            field=models.CharField(help_text='Main title on top of the page', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(help_text='Title of the page. Also appears in the navigation bar.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_nl',
            field=models.CharField(help_text='Title of the page. Also appears in the navigation bar.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_pt',
            field=models.CharField(help_text='Title of the page. Also appears in the navigation bar.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_nl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_pt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='sub_text_en',
            field=models.TextField(blank=True, help_text='Pie: text to show below the pie.', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='sub_text_nl',
            field=models.TextField(blank=True, help_text='Pie: text to show below the pie.', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='sub_text_pt',
            field=models.TextField(blank=True, help_text='Pie: text to show below the pie.', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='text_en',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='If this is a text widget, the text will be displayed in the widget. Useful for static widgets.', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='text_nl',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='If this is a text widget, the text will be displayed in the widget. Useful for static widgets.', null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='text_pt',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='If this is a text widget, the text will be displayed in the widget. Useful for static widgets.', null=True),
        ),
    ]
