# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import xf.uc_dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0010_auto_20171107_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Allows you to specify "about" information for this page, e.g. methods.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='about_en',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Allows you to specify "about" information for this page, e.g. methods.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='about_nl',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Allows you to specify "about" information for this page, e.g. methods.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='about_pt',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Allows you to specify "about" information for this page, e.g. methods.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='data_sources_en',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Specify the data sources for this page, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='data_sources_nl',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Specify the data sources for this page, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='data_sources_pt',
            field=xf.uc_dashboards.models.HTMLField(blank=True, help_text='Specify the data sources for this page, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='pagestatus',
            name='name_en',
            field=models.CharField(help_text='Name of the status.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagestatus',
            name='name_nl',
            field=models.CharField(help_text='Name of the status.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagestatus',
            name='name_pt',
            field=models.CharField(help_text='Name of the status.', max_length=150, null=True),
        ),
    ]
