# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0011_auto_20171107_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='name_en',
            field=models.CharField(help_text='The name of this perspective.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='name_nl',
            field=models.CharField(help_text='The name of this perspective.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='name_pt',
            field=models.CharField(help_text='The name of this perspective.', max_length=255, null=True),
        ),
    ]
