# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:08
from __future__ import unicode_literals

from django.db import migrations
import xf.uc_dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0015_auto_20171114_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=xf.uc_dashboards.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_en_uk',
            field=xf.uc_dashboards.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_nl_nl',
            field=xf.uc_dashboards.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_pt_pt',
            field=xf.uc_dashboards.models.HTMLField(blank=True, null=True),
        ),
    ]
