# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0008_auto_20171204_0754'),
        ('uc_dashboards', '0020_perspective_slug'),
    ]

    operations = [
    ]
