# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0023_template_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='code',
            field=models.CharField(help_text='User-defined code for this template', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('code',)]),
        ),
    ]
