# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
from xf.uc_dashboards.models.page_type import PageType


class Migration(migrations.Migration):

    def create_code(apps, schema_editor):
        for page_type in PageType.objects.all():
            page_type.code = 'pagetype-{}'.format(page_type.id)
            page_type.save()

    def remove_code(apps, schema_editor):
        pass

    dependencies = [
        ('uc_dashboards', '0024_auto_20180618_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetype',
            name='code',
            field=models.CharField(default=uuid.uuid4,help_text='User-defined code for this page type',
                                   max_length=50),
        ),
        migrations.RunPython(create_code, remove_code),
    ]
