# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0025_pagetype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetype',
            name='code',
            field=models.CharField(help_text='User-defined code for this page type', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='pagetype',
            unique_together=set([('code',)]),
        ),
    ]
