# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0027_auto_20180619_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('slug',)]),
        ),
    ]
