# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 11:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0032_auto_20180627_1346'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
