# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0034_navigationsection_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navigationsection',
            unique_together=set([('code',)]),
        ),
    ]
