# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

from xf.uc_dashboards.models import PageSection


class Migration(migrations.Migration):
    def create_code(apps, schema_editor):
        for page_section in PageSection.objects.all():
            page_section.code = 'page-section-{}'.format(page_section.id)
            page_section.save()

    def remove_code(apps, schema_editor):
        pass
    dependencies = [
        ('uc_dashboards', '0035_auto_20180628_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='code',
            field=models.CharField(default=uuid.uuid4, help_text='User-defined code for this template', max_length=50),
        ),
        migrations.RunPython(create_code, remove_code),
    ]
