# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-29 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0037_auto_20180628_1521'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
