# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('uc_dashboards', '0038_auto_20180629_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='uc_dashboards.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='groupprofile',
            unique_together=set([('group',)]),
        ),
    ]
