# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xf_system', '0008_xfsitesettings_footer_details'),
        ('uc_dashboards', '0039_auto_20180712_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='XFVizSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_perspective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymous_perspective', to='uc_dashboards.Perspective')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='xf_system.XFSiteSettings')),
            ],
        ),
    ]
