# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_dashboards', '0043_auto_20190208_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsection',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='uc_dashboards.Tag'),
        ),
    ]
